FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./vit/server_scripted_vit.py ./vit/vit_torch_script.pt ./vit/cifar10_classes.txt /code/

CMD ["gunicorn", "server_scripted_gpt:app", "--workers", "2", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8080"]