version: '3.9'
services:
  demo:
    build:
      context: .
      dockerfile: src/gradio/Dockerfile.demo
    image: gradio-cifar10-demo:latest
    container_name: gradio-demo
    expose:
      - 8080
    ports:
      - 8080:8080

    command: python3 src/gradio/demo_jit.py