version: '3.9'
services:
  demo_cifar_gradio:
    build:
      context: .
      dockerfile: src/gradio/Dockerfile.demo
    image: gradio-cifar10-demo:latest
    container_name: gradio-demo
    expose:
      - 8080
    ports:
      - 8080:8080

    command: python3 src/gradio/demo_jit_script_vit.py

  demo_gpt_gradio:
    build:
      context: .
      dockerfile: src/gradio/Dockerfile.demo_gpt_script
    image: gradio-gpt-script-demo:latest
    container_name: gradio-demo-gpt
    expose:
      - 80
    ports:
      - 8080:80

    command: python3 src/gradio/demo_jit_script_gpt.py

  demo_gpt_fastapi:
    build:
      context: .
      dockerfile: src/fastapi/gpt/Dockerfile.gpt
    image: gpt-fastapi:latest
    container_name: gpt-fastapi-demo
    expose:
      - 8080
    ports:
      - 8080:8080
    command: gunicorn server_scripted_gpt:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080

  demo_vit_fastapi:
    build:
      context: .
      dockerfile: src/fastapi/vit/Dockerfile.vit
    image: vit-fastapi:latest
    container_name: vit-fastapi-demo
    expose:
      - 8080
    ports:
      - 8080:8080
    command: gunicorn server_scripted_vit:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080

  demo_clip_fastapi:
    build:
      context: .
      dockerfile: src/clip/Dockerfile.clip
    image: clip-fastapi:latest
    container_name: clip-fastapi-demo
    expose:
      - 8080
    ports:
      - 8080:8080
    command: uvicorn server:app --host 0.0.0.0 --port 8080