FROM python:3.10-slim-buster

WORKDIR /workspace

COPY src/gradio/requirements.txt .

RUN pip3 install -r requirements.txt && rm -rf /root/.cache/pip

COPY configs /workspace/configs/
COPY ckpt /workspace/ckpt/
COPY src/gradio /workspace/src/gradio/

EXPOSE 8080

CMD [ "python3", "src/gradio/demo_jit.py"]

