FROM python:3.9

WORKDIR /code

COPY src/clip/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY src/clip/server.py /code/

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080"]