# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - paths: default.yaml
  
#   # experiment configs allow to config any model hyperparams while inference
#   # e.g. image size or num classes
#   - experiment: null

# task name, determines output directory path
task_name: "infer_jit_script_vit"

# # compile model for faster training with pytorch 2.0
# compile: False

# simply provide checkpoint path to resume training
# ckpt_path: null
ckpt_path: ${paths.root_dir}/ckpt/model_script.pt

# test image
test_path: ${paths.root_dir}/test/0000.jpg

# class labels txt
labels_path: ${paths.root_dir}/src/gradio/cifar10_classes.txt

# seed for random number generators in pytorch, numpy and python.random
seed: null

