# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: cifar10.yaml
  - model: timm_cifar10.yaml
  - paths: default.yaml
  - trainer: default.yaml
  - logger: many_loggers.yaml
  - callbacks: default.yaml
  - hydra: default.yaml
  - hparams_search: null
  - experiment: null
  
  
# task name, determines output directory path
task_name: "train"

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# Find the best learning rate and batch size
tuner: False

# compile model for faster training with pytorch 2.0
compile: False

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null

# Set True to save as Torch script mode
save_torchscript: False