FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./gpt/server_scripted_gpt.py ./gpt/gpt_torch_script.pt /code/

CMD ["gunicorn", "server_scripted_gpt:app", "--workers", "2", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8080"]